/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helloworld;

import java.sql.*;
import javax.swing.JOptionPane;

public class Payment extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static String Ticket_no;
    public static String Payment_no;
    public String Selection;
    public String book_date;
    public String Name;
    public String Sex;
    public String mobile;
    public String aadhar;
    public int age;
    public String id;

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Bank Account No.:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Bank IFSC Code");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("3D Secure Pin:");

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Amount(INR):");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ENTER YOUR DETAILS");

      // jLabel6.setText("0.00");
       

       //ID=this.Selection.substring(0,5);
       //String s1="SELECT fare FROM Flights WHERE Flight_no='"+this.ID+'"'
      // jLabel6.setText("0.00");  
        

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jPasswordField1))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void labelset() {
    	Connection ConnectionObj = null;
        Statement StatementObj = null;
        ResultSet ResultSetObj = null;
    	 
    	       	try{
    	       		   //System.out.println("In the try block Jlabel6");
    	               Class.forName("oracle.jdbc.driver.OracleDriver");
    	               ConnectionObj = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","avi141","avi123");
    	               StatementObj = ConnectionObj.createStatement();
    	               System.out.println("Before Selection");
    	               System.out.println(this.Selection);
    	               String id=this.Selection.substring(0,5);
    	               System.out.println(id);
    	               System.out.println("After Selection");
    	               String s11="SELECT * FROM Flights WHERE Flight_no='"+id+"'";
    	               ResultSetObj = StatementObj.executeQuery(s11);
    	               System.out.println("Hello");    	               
    	              System.out.println(ResultSetObj.next());
    	               String temp=ResultSetObj.getString(8);
    	               System.out.println(temp);   	               
    	               jLabel6.setText(temp);
    	               
    	       	}
    	       catch(Exception e) {
    	       	 // 	
    	       	}
    	       finally {
    	       		 try {
    	       			 StatementObj.close();
    	       			 ConnectionObj.close();
    	       		}
    	       		 catch(Exception e)
    	       		 {}
    	       		
    	       	}
    	      }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Welcome WelcomeObj = new Welcome();
        WelcomeObj.setLocationRelativeTo(null);
        WelcomeObj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ConfirmBook ConfirmBookObj = new ConfirmBook();
        ConfirmBookObj.setLocationRelativeTo(null);
        ConfirmBookObj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection ConnectionObj = null;
        Statement StatementObj = null;
        ResultSet ResultSetObj = null;
        //System.out.println("In the pay button");
        if(jTextField1.getText().equals("") || jTextField2.getText().equals("") || jPasswordField1.getPassword().equals("")){
            JOptionPane.showMessageDialog(null, "All fields are mandatory.", "Invalid", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                //System.out.println("In the try block");
                ConnectionObj = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","avi141","avi123");
                //System.out.println("In the try result Connections block");
                StatementObj = ConnectionObj.createStatement();
                //System.out.println(this.Selection);
                //System.out.println("In the try result create statememtblock");
          
                String Flight_nos = this.Selection.substring(0, 5);
                System.out.println(Flight_nos);
                System.out.println("In the try result selection block");
                int rowCount = 0;
                System.out.println("In the try result block");
               // String quer="SELECT * FROM Booked WHERE Flight_no= '"+Flight_nos+"'"+"AND BOOK='"+this.book_date+"'";
                //System.out.println(quer);
                //System.out.println(this.book_date);
                String str1="SELECT * FROM Booked WHERE Flight_no= '" + Flight_nos +"'" + "AND BOOK_DATE = '" + this.book_date + "'";
                ResultSetObj = StatementObj.executeQuery(str1);
               // boolean b=ResultSetObj.next();
                while(ResultSetObj.next()){
                    rowCount++;
                }
              //  System.out.println(rowCount);
                if(rowCount==0){
                	//System.out.println("Query Executed before");
                	String qr1="INSERT INTO Booked VALUES('"+ Flight_nos + "','" +this.book_date + "',20)";
                	System.out.println(qr1);
                    StatementObj.executeUpdate(qr1);
                 // System.out.println("Query Executed");
                }
               // ResultSetObj=StatementObj.executeQuery("SELECT Ticket_no ,Payment_no from Payment group by Payment_no")
                //this.Ticket_no= Integer.toString(Integer.parseInt(this.Ticket_no) + 1);
                
                
                //String qr3 = "Select * from Tickets where Ticket_no = '"+this.Ticket_no +"'";
               do {
            	   this.Ticket_no= Long.toString((long)Math.floor(Math.random() * (9999999999L - 1111111111 + 1)) + 1111111111);
                   String qr3 = "Select * from Tickets where Ticket_no = '"+this.Ticket_no +"'";
            	   ResultSetObj = StatementObj.executeQuery(qr3);
               }while(ResultSetObj.next());
               this.Payment_no = this.Ticket_no;
               String qr2= "INSERT INTO Tickets VALUES ('" + this.Ticket_no+ "', '"+ Flight_nos +"','"+this.Name+"','"+this.Sex+"', '"+Integer.toString(age)+"','"+this.aadhar+"','"+this.mobile+ "', '" + this.book_date + "')";
                StatementObj.executeUpdate(qr2);
               String qr3="UPDATE Booked SET seats_left=seats_left-1 WHERE Flight_no = '" +Flight_nos+"'AND book_date = '" + this.book_date+ "'";
                StatementObj.executeUpdate(qr3);
                String qr4="INSERT INTO Payment VALUES('"+this.Payment_no+"','"+this.Ticket_no+"','"+jTextField1.getText()+"')";
                StatementObj.executeUpdate(qr4);
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Ticket succesfully Booked.\nTicket Number:" + Payment.Ticket_no, "Reservation: ", JOptionPane.INFORMATION_MESSAGE);
                Welcome WelcomeObj = new Welcome();
                WelcomeObj.setLocationRelativeTo(null);
                WelcomeObj.setVisible(true);
            }
            
            catch(Exception e){
                //
            }
            finally{
                try{
                    //ConnectionObj.commit();
                    StatementObj.close();
                    ConnectionObj.close();
                    JOptionPane.showMessageDialog(null, "Ticket succesfully Booked.\nTicket Number:" + (Ticket_no+1), "Reservation: ", JOptionPane.INFORMATION_MESSAGE);
                Welcome WelcomeObj = new Welcome();
                WelcomeObj.setLocationRelativeTo(null);
                WelcomeObj.setVisible(true);
                }
                catch(Exception e){
                    //
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payment PaymentObj = new Payment();
                PaymentObj.setLocationRelativeTo(null);
                PaymentObj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
